---
logging:
  level: INFO
  loggers:
    io.dropwizard: DEBUG
database:
   driverClass: org.postgresql.Driver
   user: postgres
   password: 12345
   url: 'jdbc:postgresql://localhost:5432/Invoices'
swagger:
   resourcePackage: io.dropwizard.invoices.resources
